controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
article_list:
  path: /articles/{type}
  controller: App\Controller\ArticleController::listByType
  defaults:
    type: homme
  requirements:
    type: homme|Femme|enfant|mixte|accessoires
