controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
article_list:
  path: /articles/{type}
  controller: App\Controller\ArticleController::listByType
  defaults:
    type: homme
  requirements:
    type: homme|femme|enfant|mixte|accessoires
cart_add:
  path: /cart/add/{id}
  controller: App\Controller\CartController::addToCart
  methods: POST

cart_show:
  path: /cart
  controller: App\Controller\CartController::showCart
