services:
  App\Security\LoginFormAuthenticator:
    autowire: true
    autoconfigure: true
    public: false

  App\Controller\:
    resource: "../src/Controller"
    autowire: true
    autoconfigure: true
    public: true
